module StudentGradeManager
  VERSION: String

  class Error < StandardError
  end

  class Grade
    attr_reader subject: String
    attr_reader score: Numeric
    attr_reader coefficient: Numeric

    def initialize: (
      subject: String,
      score: Numeric,
      coefficient: Numeric
    ) -> void
  end

  class Student
    attr_reader name: String
    attr_reader grades: Array[Grade]

    def initialize: (name: String) -> void

    def add_grade: (
      subject: String,
      score: Numeric,
      coefficient: Numeric
    ) -> Grade

    def average: () -> Float

    def admitted?: () -> bool

    def mention: () -> String

    def report: () -> String
  end
end